# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nghianguyen/hdd/opt/acm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nghianguyen/hdd/opt/acm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nghianguyen/hdd/opt/acm/CMakeFiles /home/nghianguyen/hdd/opt/acm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nghianguyen/hdd/opt/acm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clip

# Build rule for target.
clip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clip
.PHONY : clip

# fast build rule for target.
clip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/build
.PHONY : clip/fast

#=============================================================================
# Target rules for targets named acm

# Build rule for target.
acm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acm
.PHONY : acm

# fast build rule for target.
acm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/build
.PHONY : acm/fast

lib/clip.o: lib/clip.cpp.o
.PHONY : lib/clip.o

# target to build an object file
lib/clip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/lib/clip.cpp.o
.PHONY : lib/clip.cpp.o

lib/clip.i: lib/clip.cpp.i
.PHONY : lib/clip.i

# target to preprocess a source file
lib/clip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/lib/clip.cpp.i
.PHONY : lib/clip.cpp.i

lib/clip.s: lib/clip.cpp.s
.PHONY : lib/clip.s

# target to generate assembly for a file
lib/clip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/lib/clip.cpp.s
.PHONY : lib/clip.cpp.s

lib/clip_x11.o: lib/clip_x11.cpp.o
.PHONY : lib/clip_x11.o

# target to build an object file
lib/clip_x11.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/lib/clip_x11.cpp.o
.PHONY : lib/clip_x11.cpp.o

lib/clip_x11.i: lib/clip_x11.cpp.i
.PHONY : lib/clip_x11.i

# target to preprocess a source file
lib/clip_x11.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/lib/clip_x11.cpp.i
.PHONY : lib/clip_x11.cpp.i

lib/clip_x11.s: lib/clip_x11.cpp.s
.PHONY : lib/clip_x11.s

# target to generate assembly for a file
lib/clip_x11.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clip.dir/build.make CMakeFiles/clip.dir/lib/clip_x11.cpp.s
.PHONY : lib/clip_x11.cpp.s

src/authenticator.o: src/authenticator.cpp.o
.PHONY : src/authenticator.o

# target to build an object file
src/authenticator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/src/authenticator.cpp.o
.PHONY : src/authenticator.cpp.o

src/authenticator.i: src/authenticator.cpp.i
.PHONY : src/authenticator.i

# target to preprocess a source file
src/authenticator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/src/authenticator.cpp.i
.PHONY : src/authenticator.cpp.i

src/authenticator.s: src/authenticator.cpp.s
.PHONY : src/authenticator.s

# target to generate assembly for a file
src/authenticator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/src/authenticator.cpp.s
.PHONY : src/authenticator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/storage_manager.o: src/storage_manager.cpp.o
.PHONY : src/storage_manager.o

# target to build an object file
src/storage_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/src/storage_manager.cpp.o
.PHONY : src/storage_manager.cpp.o

src/storage_manager.i: src/storage_manager.cpp.i
.PHONY : src/storage_manager.i

# target to preprocess a source file
src/storage_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/src/storage_manager.cpp.i
.PHONY : src/storage_manager.cpp.i

src/storage_manager.s: src/storage_manager.cpp.s
.PHONY : src/storage_manager.s

# target to generate assembly for a file
src/storage_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acm.dir/build.make CMakeFiles/acm.dir/src/storage_manager.cpp.s
.PHONY : src/storage_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... acm"
	@echo "... clip"
	@echo "... lib/clip.o"
	@echo "... lib/clip.i"
	@echo "... lib/clip.s"
	@echo "... lib/clip_x11.o"
	@echo "... lib/clip_x11.i"
	@echo "... lib/clip_x11.s"
	@echo "... src/authenticator.o"
	@echo "... src/authenticator.i"
	@echo "... src/authenticator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/storage_manager.o"
	@echo "... src/storage_manager.i"
	@echo "... src/storage_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

